# Site settings
title: Ben's Bio Portfolio
description: 
#author: bio-portfolio

# Theme
theme: minima
baseurl: ""

# Minima date format
minima:
  date_format: "%b %-d, %Y"
  header_pages: []

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
