# Site settings
title: Ben's Bio Portfolio
description: Blog detailing an Open-Sourced longevity routine, research notes, and other news
#author: bio-portfolio

# Theme
theme: minima

# Minima date format
minima:
  date_format: "%b %-d, %Y"
  header_pages: []

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
